### ISSUE TITLE
Preventing vote abuse

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#116]
**Is your feature request related to a problem? Please describe.**
As a developer, I wish to prevent a single user from upvoting or downvoting sometimes multiple times with a single account.

**Describe the solution you'd like**
Each user profile only gets one upvote or downvote on a comment or post.

**Describe alternatives you've considered**
To be considered when the issue is being approved.

**Additional context**
Blocked by #92 (Authentication)
Child issue of #182 (Modifying tasks for authentication)

**Comment by MingChen91** [comment]
@jacoballen4534  do you want to take a look at how this would work?
