### ISSUE TITLE
Deleting posts

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#118]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to able to delete posts that I don't want around anymore, as well as the comments linked to them.
**Describe the solution you'd like**
Using the delete post API(s) in the back-end to allow the front-end to add a Delete option to visible posts.

**Describe alternatives you've considered**
Can potentially consider implementing author based post deletion down the line

**Additional context**
Initial issue discussed at team meeting.
Above alternative would be blocked by issue #92 .
This will be a parent issue for separate parts of deletion. Namely, #119 (Button for deletion), #120 , (Deleting spinner), #121 (Deleting API call).

**Comment by mmir415** [comment]
@Sabatr , @kkim534  and @Akrya to review and approve issue.

**Comment by Akrya** [comment]
Approved. 👍

**Comment by mmir415** [comment]
All child issues closed, parent can also be closed
