### ISSUE TITLE
Create button for post deletion

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#119]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to have a button option to Delete posts that I want to remove. 

**Describe the solution you'd like**
This would be a front-end feature, implementing the back-end delete APIs to allow the user to delete posts.

**Describe alternatives you've considered**
To be considered when approving.

**Additional context**
Child issue of #118 (Deleting posts)
Linked to #120 (Preloading spinner), and #121 (Deleting API Call)

**Comment by mmir415** [comment]
@Sabatr , @kkim534  and @Akrya to review and approve issue.

**Comment by Sabatr** [comment]
Approved.  👍

**Comment by Akrya** [comment]
Approved. 👍

**Comment by kkim534** [comment]
I approve.
