### ISSUE TITLE
Deleting spinner (preloader)

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#120]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to have a preloader showing when I am deleting a post.
**Describe the solution you'd like**
Should show loading instantly when the delete button is clicked and stop when API is finished. Will need to store state.

**Describe alternatives you've considered**
To be considered when issue is being approved.

**Additional context**
Linked to #119 (Delete button), #121 (Deleting API Call), and #118  (Deleting posts, parent issue)

**Comment by mmir415** [comment]
@Sabatr , @kkim534  and @Akrya to review and approve issue.

**Comment by Sabatr** [comment]
Approved.  👍

**Comment by Akrya** [comment]
Approved. 👍

**Comment by kkim534** [comment]
I approve.

**Comment by mmir415** [comment]
Fixed by #145
