### ISSUE TITLE
Delete API call

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#121]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to establish an API call to the Delete Post endpoint, so that the other front-end features can utilise it. 

**Describe the solution you'd like**
API call to a Delete Post endpoint present in the Wiki.

**Describe alternatives you've considered**
N/A

**Additional context**
Linked to #120 (Delete pre-loader) , #119 (Delete button) and #118 (Deleting posts, Parent issue).

**Comment by Sabatr** [comment]
Approved.  👍 
If you are lost with this, there are examples of making async calls in the `frontend/src/services` directory.

**Comment by Akrya** [comment]
Approved. 👍

**Comment by kkim534** [comment]
I approve.

**Comment by kkim534** [comment]
Please don't merge it yet as I realised the service worker for delete post is missing.
