### ISSUE TITLE
Updating of Posts

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#122]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like the posts on Threader to be editable- users to be able to change posts after they had written them.

**Describe the solution you'd like**
Parent issue to be broken down into a button that will allow for updating, option to edit while post is being selected, a loader while the post is being edited, and an API call.

**Describe alternatives you've considered**
Not considered yet.

**Additional context**
Initial issue discussed at team meeting.
Issue will be blocked by child issues, #123  (Updating Button), #124 (Making Posts Editable while Selected), #125 (Preloader for Update), #126 (Update API call), #144 (Unit testing for updating post)

**Comment by mmir415** [comment]
@Sabatr, @saddboys and @George-E-M to review.

**Comment by saddboys** [comment]
Issue is good! I approve

**Comment by mmir415** [comment]
All child issues completed and closed. Thus, parent issue can now be closed.
