### ISSUE TITLE
Create button for updating

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#123]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to be able to have a button that lets me edit posts that have been selected.

**Describe the solution you'd like**
A button on the Post that will allow the post to be edited. It might look like a pencil or a button that says Edit.

**Describe alternatives you've considered**
Have not yet considered any alternatives, no.

**Additional context**
Child issue of #122 (Updating of posts)
Linked to #124 (Making posts editable while selected), #125 (Preloader for Update), #126 (Update API call)

**Comment by mmir415** [comment]
@Sabatr , @George-E-M and @jren791 to review.

**Comment by saddboys** [comment]
Approved as sub issue of #122

**Comment by Sabatr** [comment]
Approved 👍

**Comment by George-E-M** [comment]
Looks good to me, approved.
