### ISSUE TITLE
Making posts editable while selected

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#124]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like the posts to be editable while they are selected, with the possibility of cancelling the edits or even saving them.

**Describe the solution you'd like**
Post should be editable and saved after clicking a "save" button. onClick of save button should call the API. There should also be a cancel button. Posts should have fields prefilled when editing. 

**Describe alternatives you've considered**
To consider when approving the issue.

**Additional context**
Child issue of #122 (Updating of Posts)
Linked to #123  (Create button for Updating), #125 (Preloader during Updating), #126 (Update API call)

**Comment by mmir415** [comment]
@Sabatr , @George-E-M and @Codartizan to approve.

**Comment by saddboys** [comment]
Approved as sub issue of #122

**Comment by Sabatr** [comment]
Approved.  👍

**Comment by Codartizan** [comment]
Approved

**Comment by George-E-M** [comment]
Approved
