### ISSUE TITLE
Preloader while post is being updating

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#125]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to be able to see a preloader going when a post is being updated.

**Describe the solution you'd like**
Preloader while post is being updated. Should show instantly after clicking the "save" button and stop when API call is finished.

**Describe alternatives you've considered**
N/A

**Additional context**
Child issue of #122 (Updating Posts)
Linked to #123  (Button for Updating), #124  (Making post editable while selected), #126 (Updating API call)

**Comment by mmir415** [comment]
@Sabatr , @saddboys and @jren791 to review and approve.

**Comment by saddboys** [comment]
Approved as sub issue of #122

**Comment by Sabatr** [comment]
Approved.  👍

**Comment by Codartizan** [comment]
Approved.
