### ISSUE TITLE
Update API call

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#126]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to establish an API call to the Update Post endpoint, so that the other front-end features can utilise it.

**Describe the solution you'd like**
API call to Update Post endpoint, can be found present in the Wiki.

**Describe alternatives you've considered**

**Additional context**
Child issue of #122 (Updating Posts)

**Comment by mmir415** [comment]
@Sabatr , @nidhineshnand and @saddboys to review and approve.

**Comment by saddboys** [comment]
Approved as sub issue of #122

**Comment by Sabatr** [comment]
This isn't an issue for @nidhineshnand .

**Comment by nidhineshnand** [comment]
Just a nit, I do not think it adds much to have "Is your feature request related to a problem? Please describe" is headers to the issues. It would be better to use terms such as "Problem" as a header.

**Comment by mmir415** [comment]
I agree with your point on that matter, @nidhineshnand, it's a bit too long of a header, though it was in the issue template of the previous developers, hence why I've been maintained.
