### ISSUE TITLE
UI for the subcomments

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#128]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to provide users with an interface to see subcomments on comments that they or someone else had made.

**Describe the solution you'd like**
Users will be able to load subcomments on a comment through a user interface.

**Describe alternatives you've considered**
Developers must consider how many subcomments to load at once and how they will be loaded. There may be a button to load subcomments. There may also be a button to Load More, depending on the number of subcomments.

**Additional context**
Child issue of #127  (Implementing subcomments)
Linked to #129 (Subcomments preloader) and #130 (Loading subcomments API call)

**Comment by mmir415** [comment]
@Sabatr, @Kwu849 and @itsercleung to approve issue.

**Comment by Kwu849** [comment]
Approved

**Comment by mmir415** [comment]
@Kwu849 to extend issue with further UI implementations and edge cases.

**Comment by itsercleung** [comment]
Approved 👍
