### ISSUE TITLE
Subcomments preloader

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#129]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to have a preloader when the subcomments are loading, so as to keep my focus.

**Describe the solution you'd like**
should show a loader when the page is loading and should stop when all the API calls are finished.

**Describe alternatives you've considered**
N/A

**Additional context**
Child issue of #127 (Implementing Subcomments)
Linked to #128 (UI for subcomments) and #130 (Loading Subcomments API call)

**Comment by mmir415** [comment]
@Sabatr, @Kwu849 and @itsercleung to approve issue.

**Comment by Sabatr** [comment]
Approved.  👍

**Comment by Kwu849** [comment]
Approved

**Comment by itsercleung** [comment]
Approved
