### ISSUE TITLE
Loading subcomments API Call

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#130]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to have an API call for loading all comments at once.
**Describe the solution you'd like**
API call for loading all comments at once, most to use when loading subcomments of a comment.

**Describe alternatives you've considered**
Might have to wait on back-end to complete their implementation of this endpoint, as unlike delete APIs and update APIs,  these ones don't seem to have been completed by previous developers.

**Additional context**
Child issue of #127 (Implementing subcomments)
Linked to #128 (UI for subcomments) and #129 (Subcomments preloader)

**Comment by mmir415** [comment]
@Sabatr, @Kwu849 and @itsercleung to approve issue.

**Comment by itsercleung** [comment]
I approve

**Comment by Sabatr** [comment]
Approved.  👍

**Comment by Kwu849** [comment]
Approved

**Comment by itsercleung** [comment]
@Sabatr is it creating an api? This should be for the backend team right?

**Comment by mmir415** [comment]
Solved by #115 , closing now.
