### ISSUE TITLE
Creating a delete comment endpoint.

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#131]
**Is your feature request related to a problem? Please describe.**
Currently, comments can be added but not deleted.

**Describe the solution you'd like**
An endpoint on the backend to delete a comment from the database. 

**Describe alternatives you've considered**
Instead of removing the comment from the database and effectively deleting all reference to sub comments (replies). Just update the body of the comment to :"[deleted]". This will allow the frontend to render the message without changing any existing code.

**Additional context**
In the future make it so you need a user/ authentication to delete a comment.

**Comment by MingChen91** [comment]
@merw957 @gracecocks @RajanGuptaNZ @ElliotW1999 @ahmadumar020 @ljcnz please comment if you approve this issue. After 3 approves please remove seeking approval tag and put approved tag.

**Comment by gracecocks** [comment]
I approve :)

**Comment by merw957** [comment]
I approve

**Comment by RajanGuptaNZ** [comment]
Approved
