### ISSUE TITLE
Creating a update comment endpoint 

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#132]
**Is your feature request related to a problem? Please describe.**
Currently, comments can be added but not update/edited.

**Describe the solution you'd like**
An endpoint on the backend to update a comment from the database. 

**Describe alternatives you've considered**
Create an endpoint that takes the comment id and a new message and update it in the database

**Additional context**
In the future make it so you need a user/ authentication to update a comment.

**Comment by MingChen91** [comment]
@merw957 @gracecocks @RajanGuptaNZ @ElliotW1999 @ahmadumar020 @ljcnz please comment if you approve this issue. After 3 approves please remove seeking approval tag and put approved tag.

**Comment by gracecocks** [comment]
I approve :)

**Comment by RajanGuptaNZ** [comment]
I approve

**Comment by merw957** [comment]
I approve
