### ISSUE TITLE
Creating Test for delete comment end point

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#133]
**Is your feature request related to a problem? Please describe.**
When delete comment endpoint is created, tests will be needed.

**Describe the solution you'd like**
Create and incorporate tests for the delete comment endpoint

**Additional context**
Waiting on #131. Communicate with the dev for that issue first.

**Comment by MingChen91** [comment]
@ljcnz you wanna do the test point for this? you can approve and assign to yourself.

**Comment by ljcnz** [comment]
Sounds good, will have a chat with @merw957 about testing his endpoint :)
