### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#135]
**Is your feature request related to a problem? Please describe.**
With #115, there were a few changes to the structure of the APIs. Documentation on the wiki should be updated to reflect that.

**Describe the solution you'd like**
Look through the files under `se701-assignment1/server/src/routes/` and make sure the wiki page on API matches.

**Comment by MingChen91** [comment]
@ahmadumar020 Please check if you're happy to do this. if so you, can you remove the seeking approval label on this

**Comment by ahmadumar020** [comment]
Yea I am happy to look into this

**Comment by RajanGuptaNZ** [comment]
I've fixed the documentation for the add comment endpoint

**Comment by mmir415** [comment]
API documentation has been updated
