### ISSUE TITLE
Create New API documentation for new end points

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#136]
**Is your feature request related to a problem? Please describe.**
#131 and #132 are creating new endpoints. These need to be documented in the wiki

**Describe the solution you'd like**
Communicate with the devs working on the endpoints and update the wiki API page to include the new APIs

**Comment by MingChen91** [comment]
@RajanGuptaNZ

**Comment by RajanGuptaNZ** [comment]
Will do

**Comment by RajanGuptaNZ** [comment]
Documentation for update comment & delete comment has been added to the wiki
