### ISSUE TITLE
Unit testing for update post

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#144]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to have unit tests related to the update/edit post endpoints.

**Describe the solution you'd like**
Unit testing for front-end API calls for updating post, editing of the posts and for the UI.

**Describe alternatives you've considered**
N/A

**Additional context**
Initial feature discussed at team meeting. 
Child issue of #122 (Updating of Posts)

**Comment by mmir415** [comment]
@Codartizan  to review

**Comment by Codartizan** [comment]
Approved, Thank you.
