### ISSUE TITLE
Editing post preloader not seen or is cut short

### ISSUE THREAD

**Issue by saddboys** [SE701Group3/se701-assignment1#147]
## Expected Behavior
A loader should be seen whenever a post is edited, between the period of time when the user submits a post change and when the submission processed by the back-end.

## Current Behavior
The aforementioned loader is not seen.

## Possible Solution
Refresh only the post component, not the entire page, whenever an edit is made

## Steps to Reproduce
1. Click on any post to go into post-detail
2. Click on Edit button on that post
3. Make any edit in title or post-body
4. Submit the edit
5. The pre-loader cannot be seen, or is cut short

## Context (Environment)
Users will not be able to know if their submission for a post edit was successful or not without the pre-loader

## Detailed Description
Change the post modal to not refresh the entire screen, but call loadPosts method from the Post.jsx props.

**Comment by mmir415** [comment]
I Approve

**Comment by Sabatr** [comment]
approved 👍
