### ISSUE TITLE
Come up with UI mocks

### ISSUE THREAD

**Issue by JamesUOA** [SE701Group3/se701-assignment1#15]
**Is your feature request related to a problem? Please describe.**
As a contributor to the project, I would like a user-friendly system that anyone can pick up with ease. 

**Describe the solution you'd like**
A clean looking user interface with usability in mind.

**Comment by ErnWong** [comment]
Would be good to put the assets and designs somewhere that can be publicly accessed by people who want to work on this in the future.

**Comment by mmir415** [comment]
Has been completed by Group 6, wiki page where the UI Mocks are is here: https://github.com/SE701Group3/se701-assignment1/wiki/UI-Mock-Ups
 Closing issue now.
