### ISSUE TITLE
Add database support to handle sub-threads.

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#156]
**Is your feature request related to a problem? Please describe.**
A new feature is to have "subthreads" (Think sub-reddits) where posts can be organised into topic/interests

**Describe the solution you'd like**
An extra collection model set up to accommodate subthreads. endpoints which can create and delete could be set up as well.

**Comment by MingChen91** [comment]
@jacoballen4534

**Comment by jacoballen4534** [comment]
LGTM. Approve.
