### ISSUE TITLE
Adding a model/schema for the "users" collection in the database

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#157]
**Is your feature request related to a problem? Please describe.**
As we move forward to creating support for users. We should first set up a model in the database. 

**Describe the solution you'd like**
Follow the schema diagram on the wiki to create `users.js` schema under `se701-assignment1/server/src/db/models`

**Comment by MingChen91** [comment]
@RajanGuptaNZ

**Comment by RajanGuptaNZ** [comment]
approved
