### ISSUE TITLE
Updating existing models for posts and comments to include author

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#158]
**Is your feature request related to a problem? Please describe.**
As we move forward to include user profile support. Each comment and post should have an extra field in the database : author.

**Describe the solution you'd like**
Update the models for `/ming/se701-assignment1/server/src/db/models` for comment.js and posts.js to include a new field called author.

**Comment by MingChen91** [comment]
@ahmadumar020

**Comment by mmir415** [comment]
I approve
