### ISSUE TITLE
GET single comment

### ISSUE THREAD

**Issue by ljcnz** [SE701Group3/se701-assignment1#163]
**Is your feature request related to a problem? Please describe.**
It's frustrating that you can't fetch a single comment when you know its ID, instead having to fetch the post that it is attached to in order to view the comment tree. The reasoning behind this is it's very messing during testing to have to GET a full post and then traverse the comments tree in order to see if somethings been deleted/updated.

**Describe the solution you'd like**
A new endpoint GET /comments/{id} that returns:
* If the comment exists..
    * Return the comment in detail, with the child comment ids
    * Status code 200
* If the comment doesn't exist
    * Status code 404

**Describe alternatives you've considered**
@jacoballen4534 brought up whether or not to include the full comment tree (ie; for each sub-reply, return the full reply comment information etc) and I'm not fussed with either one. 

**Additional context**
N/A

**Comment by jacoballen4534** [comment]
LGTM approved
