### ISSUE TITLE
Store Access Token in Context

### ISSUE THREAD

**Issue by saddboys** [SE701Group3/se701-assignment1#172]
**Is your feature request related to a problem? Please describe.**
Access token needs to be stored within the program in order for authentication to work properly. This token must be accessible globally throughout the entire front-end project

**Describe the solution you'd like**
<s>Store the access token in state management.</s>
Store the access token as a cookie.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by saddboys** [comment]
Note: Upon doing this issue for a bit it is not possible to store this information in context as the information gets wiped on page refreshes, the other alternative is to use cookies, which would cause some security issues and are a temporary measure for now.

**Comment by Sabatr** [comment]
Approved
