### ISSUE TITLE
Separate endpoints to ones that need authentication and ones that don't

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#174]
**Is your feature request related to a problem? Please describe.**
Currently, all the endpoints in posts and comment are using the middleware. Some endpoints should function without authentication. 

**Describe the solution you'd like**
Separate the ones that need auth and don't.

**Describe alternatives you've considered**
The alternative is this website only works for people who are logged in. which would not be good.

**Comment by jacoballen4534** [comment]
Looks good. Approved.
