### ISSUE TITLE
Add google authentication to home page and add state

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/se701-assignment1#179]
**Is your feature request related to a problem? Please describe.**
The login button should be handled once auth succeeds. Right now it does not. 

**Describe the solution you'd like**
The google login button should simply be in the home page header. Once the JWT token is received with google response, we should handle displaying the user's name and profile picture once logged in successfully to let them know that they've logged in. 

**Additional context**
Multiple components in the login system will rely on this "hasLoggedIn" state a few features will be locked behind logging in. 
Issue discussed at team meeting.

**Comment by Sabatr** [comment]
approved 👍

**Comment by mmir415** [comment]
Approved
