### ISSUE TITLE
Modifying API calls for authentication tokens

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#181]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like the API calls from frontend need to take in the authentication tokens of the user.  They currently do not. 

**Describe the solution you'd like**
To allow for authentication credentials of the user between front-end and back-end, those credentials need to be passed from when the user logs in on front-end towards the backend. To do this, some modification would need to occur to the API calls from the front-end. This could necessitate adding extra parameters to the endpoint which take in the stored authentication token. 

**Additional context**
Blocked by #172 (Store Access Token)
Issue discussed at Team meeting.

**Comment by mmir415** [comment]
@kkim534  to review and work on.

**Comment by kkim534** [comment]
Approved
