### ISSUE TITLE
Modifying prior implemented tasks to work with authentication

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#182]
**Is your feature request related to a problem? Please describe.**
As a developer, I feel we need to now take authentication into account for other features implemented prior in the project. 

**Describe the solution you'd like**
All prior tasks implemented will need to now factor in authentication. These will especially include only allowing upvoting and downvoting once per account, only allowing signed-in users to make posts, edit posts, delete posts and comment.

**Additional context**
Blocked by #172 (Store Authentication Token)
Parent issue, discussed in team meeting.

**Comment by mmir415** [comment]
@Sabatr to review.

**Comment by Sabatr** [comment]
Approved 👍

**Comment by mmir415** [comment]
All child issues closed, parent issue can be closed
