### ISSUE TITLE
Modifying post creation for authentication

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#184]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to ensure that only signed-in users can make a post. 

**Describe the solution you'd like**
At the moment, any anonymous individual can make a post. However, if we wish to catalogue the posts, it would be much easier to have the posts linked to a user's account. This way, we can categorise all posts made by a user and even show those. Thus, it would be beneficial to ensure that only signed in users can create new posts. 

**Additional context**
Blocked by #172 (Store Auth Token)
Child issue of #182 (Modifying Tasks for Authentication)

**Comment by mmir415** [comment]
@Sabatr, @Codartizan  and @MingChen91  to review. @Codartizan to work on after review.

**Comment by MingChen91** [comment]
I Approve

**Comment by Sabatr** [comment]
Approved 👍

**Comment by Codartizan** [comment]
approved

**Comment by mmir415** [comment]
Essentially closed by #199
