### ISSUE TITLE
Modifying Post deletion with authentication

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#185]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to ensure that only signed-in users can delete a post. 

**Describe the solution you'd like**
At the moment, any anonymous individual can delete a post. However, if we wish to catalogue the posts, it would be much easier to have the posts linked to a user's account. In addition, it will prevent anonymous individuals from deleting posts without any restriction.  Thus, it would be beneficial to ensure that only signed-in users can delete posts.

**Additional context**
Blocked by #172 (Store Auth Token)
Child issue of #182 (Modifying Tasks with Authentication)

**Comment by mmir415** [comment]
@Sabatr , @MingChen91 , @jren791  to review, @jren791 to work on after approval.

**Comment by MingChen91** [comment]
I Approve

**Comment by Sabatr** [comment]
Approved 👍
