### ISSUE TITLE
Modifying post updating for authentication

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#186]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to ensure that only signed-in users can edit a post. 

**Describe the solution you'd like**
At the moment, any anonymous individual can edit a post. However, if we wish to catalogue the posts, it would be much easier to have the posts linked to a user's account. In addition, it will prevent anonymous individuals from editing posts without any restriction.  Thus, it would be beneficial to ensure that only signed-in users can edit posts.

**Additional context**
Blocked by #172 (Store Auth Token)
Child issue of #182 (Modifying Tasks for Authentication)

**Comment by mmir415** [comment]
@Sabatr , @MingChen91 , @jren791 to review the issue. @jren791 to work on issue after approval.

**Comment by MingChen91** [comment]
I Approve

**Comment by Sabatr** [comment]
Approved 👍
