### ISSUE TITLE
Modifying commenting on posts for authentication

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#187]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to ensure that only signed-in users can comment on a post. 

**Describe the solution you'd like**
At the moment, any anonymous individual can comment on a post. However, if we wish to catalogue the comments, it would be much easier to have them linked to a user's account. In addition, it will prevent anonymous individuals from commenting on posts without any restriction or identification.  Thus, it would be beneficial to ensure that only signed-in users can comment on posts.

**Additional context**
Blocked by #172 (Store Auth Token)
Child issue of #182 (Modifying Tasks for Authentication)

**Comment by mmir415** [comment]
@Sabatr , @MingChen91 and @Akrya to review. @Akrya to work on issue after approval.

**Comment by MingChen91** [comment]
I Approve

**Comment by Akrya** [comment]
I Approve 👍

**Comment by Sabatr** [comment]
Approved 👍

**Comment by mmir415** [comment]
Fixed by #162 (Firebase auth middleware), closing now
