### ISSUE TITLE
Adding username to posts for identification

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#188]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to have all posts display the usernames of those who have made the post. 

**Describe the solution you'd like**
At the moment, any anonymous individual can make a post. However, if we wish to catalogue the posts, it would be much easier to have the posts linked to a user's account. This way, we can categorise all posts made by a user and even show those. We have decided that it would be beneficial to modify posts so that only signed-in users can make them. Thus, we wish to extend that so that the usernames of the people making the posts are being displayed on the post itself.

**Additional context**
Blocked by #172 (Store Auth Token)
Child issue of #182 (Modifying Tasks for Authentication)

**Comment by mmir415** [comment]
@Sabatr , @MingChen91 and @Kwu849 to review. @Kwu849 to work on after approval.

**Comment by MingChen91** [comment]
I Approve

**Comment by Sabatr** [comment]
Approved 👍

**Comment by Kwu849** [comment]
Approve

**Comment by mmir415** [comment]
Issue closed by #200
