### ISSUE TITLE
Adding username to comments for identification

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#189]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to have all comments display the usernames of those who have made the comment. 

**Describe the solution you'd like**
At the moment, any anonymous individual can make a comment. However, if we wish to catalogue the comments, it would be much easier to have the comments linked to a user's account. This way, we can categorise all comments made by a user and even show those. We have decided that it would be beneficial to modify comments so that only signed-in users can make them. Thus, we wish to extend that so that the usernames of the people making the comments are being displayed on the comments themselves.

**Additional context**
Blocked by #172 (Store Auth Token)
Child issue of #182 (Modifying Tasks for Authentication)

**Comment by mmir415** [comment]
@Sabatr , @MingChen91 and @Kwu849 to review. @Kwu849 to work on after approval.

**Comment by MingChen91** [comment]
I Approve

**Comment by Sabatr** [comment]
Approved 👍

**Comment by Kwu849** [comment]
Approved
