### ISSUE TITLE
Add tests for posts endpoints

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#194]
**Is your feature request related to a problem? Please describe.**
As the post endpoint have been updated to include user details, the tests should be updated to reflect such.

**Describe the solution you'd like**
- check that the user email is recorded when adding a post
- check that in order to delete a comment the caller has to the be post author
- check that in order to update a comment the caller has to the be post author

**Describe alternatives you've considered**
Not do this and have incomplete tests coverage.

**Comment by williamlixu** [comment]
Hey Liam how is progressing looking on this , I think there is a code cutoff at midnight :)

**Comment by williamlixu** [comment]
Hey @ljcnz, how is progressing looking on this? I think there is a code cutoff at midnight :)

**Comment by ljcnz** [comment]
Hey William, thanks for bumping this issue up. After discussing with @MingChen91, we decided to not go through with adding these tests :^)
