### ISSUE TITLE
Include user name in the database

### ISSUE THREAD

**Issue by MingChen91** [SE701Group3/se701-assignment1#197]
**Is your feature request related to a problem? Please describe.**
Currently, the backend only stores user email, it would look better on frontend if the user name was also stored and we are able to display the username.

**Describe the solution you'd like**
- update the database to include user name
- when creating a user make sure to include user name
- add an endpoint for displaying user information

**Comment by MingChen91** [comment]
@Sabatr  @mmir415  @jacoballen4534

**Comment by mmir415** [comment]
I approve

**Comment by Sabatr** [comment]
approved 👍
