### ISSUE TITLE
Hide login button on successful authentication

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/se701-assignment1#204]
**Is your feature request related to a problem? Please describe.**
The login button seems to appear on refresh even if the user is authenticated and "logged in"

**Describe the solution you'd like**
To no display the login button once the user has logged in and refreshed the page

**Additional context**
Another issue should deal with user login detail state may need to be passed by using the token stored in local state.

**Comment by mmir415** [comment]
I approve
