### ISSUE TITLE
Feature to display persisted user account information

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/se701-assignment1#206]
**Is your feature request related to a problem? Please describe.**
User account info is not showing up once logged in. Users would like to confirm that they are logged in however.

**Describe the solution you'd like**
Showing name and user profile picture where login button once was

**Additional context**
N/A

**Comment by mmir415** [comment]
I Approve

**Comment by MingChen91** [comment]
approve

**Comment by Sabatr** [comment]
Approved
