### ISSUE TITLE
Fixing security vulnerability for minimist

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/se701-assignment1#211]
**Is your feature request related to a problem? Please describe.**
As a project administrator, I would prefer to have no security vulnerabilities in our project, as those may open us up to attacks. 

**Describe the solution you'd like**
The vulnerability itself stems from the version of minimist that we are using in our ./server folder.  The version we have is 1.2.0, and the vulnerability should be fixed if we update to version 1.2.5. A developer could manually update this dependency in our package.json file.

**Describe alternatives you've considered**
An alternative way to fix it would be to do npm update -depth 5, which would update several of the dependencies in package.json automatically. The problem with this would be if certain dependencies got updated in a manner that would negatively impact the project itself.

**Additional context**
Issue was discussed in team meeting.

**Comment by mmir415** [comment]
I approve

**Comment by mmir415** [comment]
Issue solved by #210 , closing now

**Comment by ahmadumar020** [comment]
Issue has been looked into.
