### ISSUE TITLE
Implement create-post page

### ISSUE THREAD

**Issue by ErnWong** [SE701Group3/se701-assignment1#35]
**Is your feature request related to a problem? Please describe.**
As a user, I want a page where I can create a new post, so that I can share my ideas to the world.

**Additional context**
1. We will first investigate the [material ui](https://material-ui.com/) that may be useful, and prototype something.
2. We will then wait for the designs to be supplied by @JamesUOA (#15)
3. In the meantime, we will look into writing tests as appropriate.
4. We can look into ~~creating mock data for the component~~ (EDIT: There's no mock data needed), as well as prototyping the interactions with the server according to the [API spec](https://github.com/se701-group6/se701-assignment1/wiki/API) as it currently stands.

**Dependencies**
Blocked by #15
~~Will also need a testing framework in place.~~ EDIT: I forgot that there's already Jest set up.
Child issues: #38 and #39

**Comment by mmir415** [comment]
Issue has been completed by Group 6, closing now
