### ISSUE TITLE
Set up Posts routes

### ISSUE THREAD

**Issue by andrewh318** [SE701Group3/se701-assignment1#41]
**Is your feature request related to a problem? Please describe.**
As a developer, I want to create the CRUD endpoints for Posts so that incoming requests can be processed.

**Describe the solution you'd like**
- Implement the Posts API's specified in the [wiki ](https://github.com/se701-group6/se701-assignment1/wiki/API)
- This will also require updating the Post Model to match the API proposal.

**Describe alternatives you've considered**
N/A

**Additional context**
* Our Post Model unit tests should be updated to match the new schema 
* Integration tests should be added for all the CRUD endpoints

**Comment by mmir415** [comment]
Issue has been completed by Group 6, closing now
