### ISSUE TITLE
Implement post-detail page

### ISSUE THREAD

**Issue by FrankWangma** [SE701Group3/se701-assignment1#42]
**Is your feature request related to a problem? Please describe.**
As a user, I want a page where I can start discussions about a post, so that I can have intellectual conversations

**Describe the solution you'd like**
* Need to link the API to the page
* Implement the visual interface

**Describe alternatives you've considered**
N/A

**Additional context**
1. Research the [material ui](https://material-ui.com/) page and design some basic prototypes for the layout
2. We will then wait for the designs to be supplied by @JamesUOA (#15)
3. This Issue has sub-issues which will need to be completed before it can be considered complete

**Dependencies**
Blocked by #15
Child Issues: #43 and #44

**Comment by MingChen91** [comment]
Already implemented by previous developers. Closing
