### ISSUE TITLE
Create a React component for the post-details page

### ISSUE THREAD

**Issue by FrankWangma** [SE701Group3/se701-assignment1#44]
**Is your feature request related to a problem? Please describe.**
As a user, I want a visible interface for viewing and commenting on posts.

**Describe the solution you'd like**
A visual interface that is shown when a post is clicked on the front page. 
Ideally, this should have:
*A way to comment
*Tree-style comment structure
*Body and title for the post

**Describe alternatives you've considered**
Not Applicable.

**Additional context**
Reference to #42

**Comment by MingChen91** [comment]
Already implemented by previous developers. Closing
