### ISSUE TITLE
Add list of comments property to POST schema

### ISSUE THREAD

**Issue by clyanide** [SE701Group3/se701-assignment1#54]
**Is your feature request related to a problem? Please describe.**
As a developer, I want to add a list of comments to the POST schema so that the comments related to the post can be accessed.

**Describe the solution you'd like**

- Create a comments schema
- Add the comments property to the POST schema

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by mmir415** [comment]
Issue declared invalid, closing now
