### ISSUE TITLE
Create comment container for Post-Details

### ISSUE THREAD

**Issue by FrankWangma** [SE701Group3/se701-assignment1#67]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to see comments on posts that I go into
**Describe the solution you'd like**
I want Tree-style comments, where I can see comments that are made on other comments

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JamesUOA** [comment]
I approve

**Comment by mmir415** [comment]
Issue has been satisfied by #66 , closing now
