### ISSUE TITLE
Documentation Coverage Sweep

### ISSUE THREAD

**Issue by ErnWong** [SE701Group3/se701-assignment1#89]
**Is your feature request related to a problem? Please describe.**
As a contributor, I want a complete set of documentation, so I can find the information I need to contribute effectively.

**Describe the solution you'd like**
Perform a sweep on the wiki and add documentation tasks for anything missing, lacking, or needs fixing, onto this GitHub Project here: https://github.com/se701-group6/se701-assignment1/projects/2

**Comment by ParieMalhotra** [comment]
I approve

**Comment by timovv** [comment]
I approve

Cheers,
Timo

**Comment by joshiefu** [comment]
I approve

**Comment by mmir415** [comment]
Issue has been satisfied by Group 6, closing now
