### ISSUE TITLE
Introduce subthreaders - pages for threads about specific topics

### ISSUE THREAD

**Issue by ErnWong** [SE701Group3/se701-assignment1#99]
**Is your feature request related to a problem? Please describe.**
As a user, I want places where users like me can post about a certain topic, so that I don't have to search through all threads about every topic to find the posts that I care about.

**Describe the solution you'd like**
To be discussed before approving this issues.

**Describe alternatives you've considered**
To do.

**Additional context**
This was one of the features discussed in the initial meeting.

Parent issue of #151 (Adding subthreaders to main page), #152  (subthreader creation) #153 (adding subthread option to post) #154 (adding subthread deletion)

**Comment by mmir415** [comment]
@nidhineshnand  to review this parent issue.

**Comment by mmir415** [comment]
All being worked on child issues closed, parent issue can now be closed
